### ISSUE TITLE
Support for non GUI users

### ISSUE THREAD

**Issue by fabrizio8** [z-Wind/schwab_api#1]
Seems like the only way to authorize with the API is to try opening the authorization url in the host running the code.
It would be nice if a manual authorization flow like the one in schwab-py was supported, where the authorization URL can be loaded into a different host and the callback URL can be provided via CLI.

As a workaround, is it possible to just provide a refresh token and pick up the authorization flow from there?
I tried to do this myself and it just ends up on the `rx.recv().await.expect("receive code")` line of `local_server`, infinitely waiting for a message.

I could help with implementing this. Just not sure where to start.

**Comment by z-Wind** [comment]
I don't understand what you mean. Are you suggesting logging in and authenticating on a different machine? If so, the local_server must be changed to an external one because it currently only handles local auth codes. Alternatively, you could implement your own `Tokener` and pass it to `api::Api::new`.

**Comment by fabrizio8** [comment]
This is what it looks like on schwab-py. Source is [here](https://github.com/alexgolec/schwab-py/blob/main/schwab/auth.py#L501)

```
No token found, creating...

**************************************************************

This is the manual login and token creation flow for schwab-py.
Please follow these instructions exactly:

 1. Open the following link by copy-pasting it into the browser
    of your choice:

        https://api.schwabapi.com/v1/oauth/authorize?response_type=code&client_id=<CLIENT_ID>&redirect_uri=https%3A%2F%2F127.0.0.1&state=<STATE>

 2. Log in with your account credentials. You may be asked to
    perform two-factor authentication using text messaging or
    another method, as well as whether to trust the browser.

 3. When asked whether to allow your app access to your account,
    select "Allow".

 4. Your browser should be redirected to your callback URI. Copy
    the ENTIRE address, paste it into the following prompt, and press
    Enter/Return.

If you encounter any issues, see here for troubleshooting:
https://schwab-py.readthedocs.io/en/latest/auth.html#troubleshooting

**************************************************************

Redirect URL> <Input goes here>
```

Not sure if the oauth2 crate for rust provides the same features used in schwab-py.
I'll try a different Tokener implementation. Thanks for the tip and quick response :)

**Comment by fabrizio8** [comment]
Not sure how to approach the schwab-py method, but it looks like by adding more redirect URIs to the api app settings I'll be able to do this.

**Comment by z-Wind** [comment]
You can try this 62db905ffaf6275352bc29c58ff8d300a31d9644.
